---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pull-requests: read
  packages: read
  security-events: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/app-ci.yaml@ea69922ce6a34b643f3009699517d5c788314dd4 # v2.0.1
