---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  ci:
    permissions:
      actions: read
      contents: write
      pull-requests: read
      packages: read
      security-events: write
    uses: erik73/workflows/.github/workflows/app-ci.yaml@ea69922ce6a34b643f3009699517d5c788314dd4 # v2.0.1

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: erik73/workflows/.github/workflows/app-deploy.yaml@ea69922ce6a34b643f3009699517d5c788314dd4 # v2.0.1
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
