---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/pr-labels.yaml@ea69922ce6a34b643f3009699517d5c788314dd4 # v2.0.1
